support ComponentArrays
TuringLang/AdvancedHMC.jl pull request #257
Opened 2021-04-01 13:10 UTC by scheidan

Implements #253.
Please let me know if I shoudl change something.

2021-04-06 07:04 UTC, scheidan commented
Some CI tests failed but I think it has nothing to do with this commit. Unfortuantlay it  says only `This check failed` when clicking on details... 

Locally the tests pass.

2021-04-09 12:44 UTC, xukai92 requested changes

2021-04-09 12:44 UTC, xukai92 commented on src/hamiltonian.jl
> +function phasepoint(
Can you implement your change while keeping the current interface of optionally provide `ℓπ` and `ℓκ`?
You can create a function for your version of initializing `r`, e.g. `safe_rsimilar(θ, _r) = (r = similar(θ); copyto!(r, _r); r)`, and update `r=safe_rsimilar((θ, _r))`

2021-04-09 12:46 UTC, xukai92 commented
Thanks for the PR. 
The proposed way to support ComponentArrays looks great to me.
But the current implementation changes the interface, which is not desirable.
Please check my comments on addressing this.

Also, can you add a test with the use case of ComponentArrays so that we know this PR works as expected?
The example you have in https://github.com/TuringLang/AdvancedHMC.jl/issues/253 should be good enough.
You should be able to add packages only for testing purposes in the `[extras]` section in the Project.toml file.

2021-04-12 14:47 UTC, scheidan commented
Thanks for your review @xukai92! Your suggestion made a lot of sense.

2021-04-12 21:35 UTC, xukai92 approved these changes

2021-04-12 21:36 UTC, xukai92 commented
Great! The changes look good to me. 
It's quite neat to have ComponentArray offically supported in AHMC.
Thanks for the PR again!

2021-04-12 21:36 UTC, merged