add definitions to readme
TuringLang/AdvancedHMC.jl pull request #296
Opened 2022-09-24 10:50 UTC by SaranjeetKaur

2022-09-24 10:54 UTC, SaranjeetKaur commented
@xukai92, @yebai - please review the above descriptions in the README and let me know your comments.

2022-09-26 00:39 UTC, xukai92 reviewed
I really like the detailed content but I feel it may be a little bit too techinical to start with (as in the README). Maybe we could use the `details` tag (https://www.w3schools.com/tags/tag_details.asp) to make the math part expand when clicked?

2022-09-26 03:46 UTC, SaranjeetKaur commented
@xukai92 - nice idea! I've made the changes, please have a look and let me know if it looks ok or any change is needed

2022-09-28 13:33 UTC, xukai92 commented on README.md
> + The Euclidean metric is also known as the mass matrix in the physical perspective. For available metrics refer [Hamiltonian mass matrix](https://github.com/SaranjeetKaur/AdvancedHMC.jl#hamiltonian-m
```suggestion
 The Euclidean metric is also known as the mass matrix in the physical perspective. For available metrics refer <a href="https://github.com/SaranjeetKaur/AdvancedHMC.jl#hamiltonian-mass-matrix-metric">Hamiltonian mass matrix</a>.
```

2022-09-28 13:34 UTC, xukai92 commented on README.md
> + Suppose ${\bf x}$ and ${\bf v}$ are the position and velocity of an individual particle respectively; $i$ and $i+1$ are the indices for time values $t_i$ and $t_{i+1}$ respectively; $dt = t_{i+1} -
```suggestion
 Suppose ${\bf x}$ and ${\bf v}$ are the position and velocity of an individual particle respectively; $i$ and $i+1$ are the indices for time values $t_i$ and $t_{i+1}$ respectively; $dt = t_{i+1} - t_i$ is the time step size (constant and regularly spaced intervals); and ${\bf a}$ is the acceleration induced on a particle by the forces of all other particles. Furthermore, suppose positions are defined at times $t_i, t_{i+1}, t_{i+2}, \dots $, spaced at constant intervals $dt$, the velocities are defined at halfway times in between, denoted by $t_{i-1/2}, t_{i+1/2}, t_{i+3/2}, \dots $, where $t_{i+1} - t_{i + 1/2} = t_{i + 1/2} - t_i = dt / 2$, and the accelerations ${\bf a}$ are defined only on integer times, just like the positions. Then the leapfrog integration scheme is given as: $x_{i} = x_{i-1} + v_{i-1/2} dt; \quad v_{i+1/2} = v_{i-1/2} + a_i dt$. For available integrators refer <a href="https://github.com/SaranjeetKaur/AdvancedHMC.jl#integrator-integrator">Integrator</a>.
```

2022-09-28 13:34 UTC, xukai92 commented on README.md
> + In the classical HMC approach, during the first step, new values for the momentum variables are randomly drawn from their Gaussian distribution, independently of the current values of the position v
```suggestion
 In the classical HMC approach, during the first step, new values for the momentum variables are randomly drawn from their Gaussian distribution, independently of the current values of the position variables. Whereas, during the second step, a Metropolis update is performed, using Hamiltonian dynamics to provide a new state. For available proposals refer <a href="https://github.com/SaranjeetKaur/AdvancedHMC.jl#proposal-proposal">Proposal</a>.
```

2022-09-28 13:48 UTC, SaranjeetKaur commented on README.md
> + The Euclidean metric is also known as the mass matrix in the physical perspective. For available metrics refer [Hamiltonian mass matrix](https://github.com/SaranjeetKaur/AdvancedHMC.jl#hamiltonian-m
good catch! thanks for that!

2022-09-28 13:54 UTC, xukai92 submitted a review, later dismissed

2022-09-28 13:56 UTC, yebai requested changes

2022-09-28 13:56 UTC, yebai commented on README.md
> + The Euclidean metric is also known as the mass matrix in the physical perspective. For available metrics refer <a href="https://github.com/SaranjeetKaur/AdvancedHMC.jl#hamiltonian-mass-matrix-metric
We need to avoid these hard-coded links: `https://github.com/SaranjeetKaur/AdvancedHMC.jl`. There are a few more in other places.

2022-09-28 14:12 UTC, SaranjeetKaur commented
@yebai - have updated it now

2022-09-28 17:40 UTC, merged